load("//libraries/tools:tool_launchers.bzl", "executable_tool_launcher")

executable_tool_launcher(
    name = "outlineviewer",
    base_repo_name = "bazelrio_org_wpilib_tools_outlineviewer",
    macos_app = "OutlineViewer.app",
)
