load("@rules_cc//cc:defs.bzl", "cc_library")

alias(
    name = "header_files",
    actual = "@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_headers//:header_files",
    visibility = ["@bzlmodrio-allwpilib//:__subpackages__"],
)

cc_library(
    name = "shared_interface",
    srcs = select({
        "@rules_bzlmodrio_toolchains//conditions:windows_arm64": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_windowsarm64//:shared_interface"],
        "@rules_bzlmodrio_toolchains//conditions:windows_arm64_debug": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_windowsarm64debug//:shared_interface"],
        "@rules_bzlmodrio_toolchains//conditions:windows_x86_64": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_windowsx86-64//:shared_interface"],
        "@rules_bzlmodrio_toolchains//conditions:windows_x86_64_debug": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_windowsx86-64debug//:shared_interface"],
    }),
    linkstatic = True,
    tags = ["manual"],
    visibility = ["@bzlmodrio-allwpilib//:__subpackages__"],
    deps = ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_headers//:headers"],
)

filegroup(
    name = "shared_raw",
    srcs = select({
        "@rules_bzlmodrio_toolchains//conditions:linux_x86_64": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_linuxx86-64//:shared"],
        "@rules_bzlmodrio_toolchains//conditions:linux_x86_64_debug": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_linuxx86-64debug//:shared"],
        "@rules_bzlmodrio_toolchains//conditions:osx": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_osxuniversal//:shared"],
        "@rules_bzlmodrio_toolchains//conditions:osx_debug": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_osxuniversaldebug//:shared"],
        "@rules_bzlmodrio_toolchains//conditions:windows_arm64": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_windowsarm64//:shared"],
        "@rules_bzlmodrio_toolchains//conditions:windows_arm64_debug": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_windowsarm64debug//:shared"],
        "@rules_bzlmodrio_toolchains//conditions:windows_x86_64": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_windowsx86-64//:shared"],
        "@rules_bzlmodrio_toolchains//conditions:windows_x86_64_debug": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_windowsx86-64debug//:shared"],
        "@rules_bzlmodrio_toolchains//constraints/is_bookworm64:bookworm64": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_linuxarm64//:shared"],
        "@rules_bzlmodrio_toolchains//constraints/is_bookworm64:bookworm64_debug": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_linuxarm64debug//:shared"],
        "@rules_bzlmodrio_toolchains//constraints/is_systemcore:systemcore": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_linuxsystemcore//:shared"],
        "@rules_bzlmodrio_toolchains//constraints/is_systemcore:systemcore_debug": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_linuxsystemcoredebug//:shared"],
        "//conditions:default": [],
    }),
    visibility = ["@bzlmodrio-allwpilib//:__subpackages__"],
)

cc_library(
    name = "shared",
    srcs = [":shared_raw"],
    visibility = ["@bzlmodrio-allwpilib//:__subpackages__"],
    deps = [
        "@bzlmodrio-allwpilib//libraries/cpp/wpilibc:shared",
    ] + select({
        "@rules_bzlmodrio_toolchains//conditions:windows_arm64": [":shared_interface"],
        "@rules_bzlmodrio_toolchains//conditions:windows_x86_64": [":shared_interface"],
        "//conditions:default": [],
    }) + ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_headers//:headers"],
    alwayslink = 1,
)

cc_library(
    name = "static",
    linkstatic = 1,
    visibility = ["@bzlmodrio-allwpilib//:__subpackages__"],
    deps = ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_headers//:headers"] + select({
        "@rules_bzlmodrio_toolchains//conditions:linux_x86_64": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_linuxx86-64static//:static_libs"],
        "@rules_bzlmodrio_toolchains//conditions:linux_x86_64_debug": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_linuxx86-64staticdebug//:static_libs"],
        "@rules_bzlmodrio_toolchains//conditions:osx": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_osxuniversalstatic//:static_libs"],
        "@rules_bzlmodrio_toolchains//conditions:osx_debug": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_osxuniversalstaticdebug//:static_libs"],
        "@rules_bzlmodrio_toolchains//conditions:windows_arm64": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_windowsarm64static//:static_libs"],
        "@rules_bzlmodrio_toolchains//conditions:windows_arm64_debug": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_windowsarm64staticdebug//:static_libs"],
        "@rules_bzlmodrio_toolchains//conditions:windows_x86_64": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_windowsx86-64static//:static_libs"],
        "@rules_bzlmodrio_toolchains//conditions:windows_x86_64_debug": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_windowsx86-64staticdebug//:static_libs"],
        "@rules_bzlmodrio_toolchains//constraints/is_bookworm64:bookworm64": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_linuxarm64static//:static_libs"],
        "@rules_bzlmodrio_toolchains//constraints/is_bookworm64:bookworm64_debug": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_linuxarm64staticdebug//:static_libs"],
        "@rules_bzlmodrio_toolchains//constraints/is_systemcore:systemcore": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_linuxsystemcorestatic//:static_libs"],
        "@rules_bzlmodrio_toolchains//constraints/is_systemcore:systemcore_debug": ["@bazelrio_org_wpilib_xrpvendordep_xrpvendordep-cpp_linuxsystemcorestaticdebug//:static_libs"],
    }),
)
