alias(
    name = "DataLogTool",
    actual = "@bzlmodrio-allwpilib//libraries/tools/datalogtool",
    tags = [
        "no-bookworm64",
        "no-bullseye32",
        "no-bullseye64",
        "no-systemcore",
    ],
)

alias(
    name = "Glass",
    actual = "@bzlmodrio-allwpilib//libraries/tools/glass",
    tags = [
        "no-bookworm64",
        "no-bullseye32",
        "no-bullseye64",
        "no-systemcore",
    ],
)

alias(
    name = "OutlineViewer",
    actual = "@bzlmodrio-allwpilib//libraries/tools/outlineviewer",
    tags = [
        "no-bookworm64",
        "no-bullseye32",
        "no-bullseye64",
        "no-systemcore",
    ],
)

alias(
    name = "processstarter",
    actual = "@bzlmodrio-allwpilib//libraries/tools/processstarter",
    tags = [
        "no-bookworm64",
        "no-bullseye32",
        "no-bullseye64",
        "no-systemcore",
    ],
)

alias(
    name = "SysId",
    actual = "@bzlmodrio-allwpilib//libraries/tools/sysid",
    tags = [
        "no-bookworm64",
        "no-bullseye32",
        "no-bullseye64",
        "no-systemcore",
    ],
)

alias(
    name = "wpical",
    actual = "@bzlmodrio-allwpilib//libraries/tools/wpical",
    tags = [
        "no-bookworm64",
        "no-bullseye32",
        "no-bullseye64",
        "no-systemcore",
    ],
)
