load("@rules_java//java:defs.bzl", "java_import")

java_import(
    name = "tunables",
    jars = ["@org_wpilib_tunables_tunables_java//jar:file"],
    visibility = ["//visibility:public"],
    deps = [
        "@bzlmodrio-allwpilib//libraries/cpp/tunables:jni",
        "@bzlmodrio-allwpilib//libraries/cpp/wpiutil:jni",
        "@bzlmodrio-allwpilib//libraries/java/wpiutil",
    ],
)
