load("//libraries/tools:tool_launchers.bzl", "executable_tool_launcher")

executable_tool_launcher(
    name = "roborioteamnumbersetter",
    base_repo_name = "bazelrio_org_wpilib_tools_roborioteamnumbersetter",
    macos_app = "roboRIOTeamNumberSetter.app",
)
