load("//libraries/tools:tool_launchers.bzl", "executable_tool_launcher")

executable_tool_launcher(
    name = "wpical",
    base_repo_name = "bazelrio_org_wpilib_tools_wpical",
    macos_app = "wpical.app",
)
