load("//libraries/tools:tool_launchers.bzl", "executable_tool_launcher")

executable_tool_launcher(
    name = "glass",
    base_repo_name = "bazelrio_org_wpilib_tools_glass",
    macos_app = "Glass.app",
)
