load("//libraries/tools:tool_launchers.bzl", "java_tool_launcher")

java_tool_launcher(
    name = "Shuffleboard",
    base_repo_name = "bazelrio_edu_wpi_first_tools_shuffleboard",
    main_class = "edu.wpi.first.shuffleboard.app.Main",
)
