load("//libraries/tools:tool_launchers.bzl", "executable_tool_launcher")

executable_tool_launcher(
    name = "processstarter",
    base_repo_name = "bazelrio_org_wpilib_tools_processstarter",
    macos_app = "processstarter.app",
)
