load("//libraries/tools:tool_launchers.bzl", "java_tool_launcher")

java_tool_launcher(
    name = "PathWeaver",
    base_repo_name = "bazelrio_org_wpilib_tools_pathweaver",
    main_class = "edu.wpi.first.pathweaver.Main",
)
