load("//libraries/tools:tool_launchers.bzl", "executable_tool_launcher")

executable_tool_launcher(
    name = "datalogtool",
    base_repo_name = "bazelrio_edu_wpi_first_tools_datalogtool",
    macos_app = "DataLogTool.app",
)
