name: Auto Update
on: [pull_request, push]
# on:
#   workflow_dispatch:
#   push:
#     tags:
#     - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish_module:
    name: "Publish Module"
    runs-on: ubuntu-latest
    steps:
    # Checkout repository
    - uses: actions/checkout@v3
      with:
        path: libraries/bzlmodrio-allwpilib

    # Checkout gentool
    - uses: actions/checkout@v3
      with:
        repository: 'bzlmodRio/gentool.git'
        fetch-depth: 0
        path: gentool
        ref: refactor_dev

    # Checkout bzlmodrio-opencv
    - uses: actions/checkout@v3
      with:
        repository: 'bzlmodRio/bzlmodrio-opencv.git'
        fetch-depth: 0
        path: libraries/bzlmodrio-allwpilib/../../libraries/bzlmodRio-opencv
        ref: refactor_dev

    # Checkout bzlmodrio-ni
    - uses: actions/checkout@v3
      with:
        repository: 'bzlmodRio/bzlmodrio-ni.git'
        fetch-depth: 0
        path: libraries/bzlmodrio-allwpilib/../../libraries/bzlmodRio-ni
        ref: refactor_dev



    # Run update
    - run: bazel run //:auto_update
      working-directory: libraries/bzlmodrio-allwpilib/generate

    # Create pull requests
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      env:
        GITHUB_TOKEN: ${{ secrets.AUTO_UPDATE_KEY }}
      with:
        path: libraries/bzlmodrio-allwpilib
        base: refactor_dev
        token: ${{ secrets.AUTO_UPDATE_KEY }}
        reviewers: pjreiniger
        branch: autoupdate
        title: "Auto-update"
