name: Auto Update
on: [pull_request, push]
# on:
#   workflow_dispatch:
#   push:
#     tags:
#     - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish_module:
    name: "Publish Module"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
      id: go

    - uses: actions/checkout@v3

    - name: Install Buildifier
      run: |
        cd $(mktemp -d)
        GO111MODULE=on go get github.com/bazelbuild/buildtools/buildifier@6.0.0

    # Checkout repository
    - uses: actions/checkout@v3
      with:
        path: libraries/bzlmodrio-allwpilib

    # Checkout gentool
    - uses: actions/checkout@v3
      with:
        repository: 'bzlmodRio/gentool.git'
        fetch-depth: 0
        path: gentool
        ref: refactor_dev

    # Checkout bzlmodrio-opencv
    - uses: actions/checkout@v3
      with:
        repository: 'bzlmodRio/bzlmodrio-opencv.git'
        fetch-depth: 0
        path: libraries/bzlmodrio-allwpilib/../../libraries/bzlmodRio-opencv
        ref: refactor_dev

    # Checkout bzlmodrio-ni
    - uses: actions/checkout@v3
      with:
        repository: 'bzlmodRio/bzlmodrio-ni.git'
        fetch-depth: 0
        path: libraries/bzlmodrio-allwpilib/../../libraries/bzlmodRio-ni
        ref: refactor_dev



    # Run update
    - name: Run update
      run: bazel run //:auto_update
      working-directory: libraries/bzlmodrio-allwpilib/generate

    - name: Generate if changed TEMP
      run: git --no-pager diff --exit-code HEAD
      working-directory: libraries/bzlmodrio-allwpilib/generate

    - name: Generate if changed
      run: | 
        bazel run //:generate
        buildifier --lint=fix -r ..
      working-directory: libraries/bzlmodrio-allwpilib/generate
      if: ${{ failure() }}


    # Create pull requests
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      if: ${{ always() }}
      env:
        GITHUB_TOKEN: ${{ secrets.AUTO_UPDATE_KEY }}
      with:
        path: libraries/bzlmodrio-allwpilib
        base: refactor_dev
        token: ${{ secrets.AUTO_UPDATE_KEY }}
        reviewers: pjreiniger
        branch: autoupdate
        title: "Auto-update"
